### ISSUE TITLE
Classe generica gestione DB

### ISSUE THREAD

**Issue by RedsAnDev** [STB1019/Flutter-RemoteTree#1]
## Scenario

La classe astratta del DB deve permettere l'utilizzo della tabella con semplicità. Probabilmente servono dei metodi di serializzazione degli oggetti.

**Comment by MassimilianoT** [comment]
Da fare necessariamente una modifica alla struttura del progetto per simulare un db prima di inserirlo in modo effettivo.
initState(){} della prima pagina della app effettua un fetch dal db e in attesa mostra un circular indicator. Serve una classe di appoggio, attraverso questa classe poi utilizzare la funzione map sulla struttura dati contenente le sezioni per generare il widget Sezione in funzione di alcuni parametri per esempio un parametro String che permette all'utente di scegliere tra i template

**Comment by MassimilianoT** [comment]
Per ora il progetto è ad un buono stadio da questo punto di vista
Il passaggio finale nel lavoro del DB è 
- Table Utente-PSW -> Salvare il log utente usando crittografia con funzione di hash (figo vediamo se è possibile) [package crypto]
- Table Sezione -> E' necessario inserire 2 nuove colonne. Una per differenziare le varie sezioni tramite un intero che fa riferimento ad un enum o con una stringa. Una invece per le opzioni delle singole sezioni che possono variare, utilizzo una stringa json originata da una mappa diversa per ogni tipologia di sezione

Potrei creare una piccola app in flutter che crea gli elementi del DB. Non sono sicuro, parlane con Andrea

**Comment by RedsAnDev** [comment]
@MassimilianoT quale design pattern pensi di usare? https://fluttersamples.com

**Comment by MassimilianoT** [comment]
@RedsAnDev Non ci avevo ancora riflettuto, per ora ho buttato giù una rozza gestione del DB per capirne il funzionamento e una serie di sezioni base. Grazie mille del link, ci ragiono. In caso domani mattina o alla riunione successiva ti chiedo consigli. Per il momento ho usato comunque una sorta di Model View Provider

**Comment by MassimilianoT** [comment]
Per ora la struttura del DB funziona tuttavia non mi piace. Vorrei trovare un metodo migliore per memorizzare le sezioni
