### ISSUE TITLE
V 0.0.1

### ISSUE THREAD

**Issue by RedsAnDev** [STB1019/Flutter-RemoteTree#2]
- [ ] Gestione del DB in locale
- [ ] Aggiornare da remoto il DB

**Comment by MassimilianoT** [comment]
DB locale in buono stato

**Comment by MassimilianoT** [comment]
DB Locale lavora con unica stringa json che contiene tutte le section divise in gruppi per tipologia. L'ordinamento nello scroll infinito è dato dall'id della sezione
